version: "3.8"
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=product
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - "./volumes/mysql:/var/lib/mysql"
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
